
name: Deploy to Replit
on:
  push:
    branches: [ dev ]  # Deploy when pushing to dev branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Replit Production
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.REPLIT_DEPLOYMENT_URL }}
